version: "3"
name: "bili-live-spider"
services:
  proxy:
    network_mode: "host"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "50M"
      replicas: 6
    image: dperson/torproxy
    expose:
      - 9050
      - 9051
    environment:
      TOR_NewCircuitPeriod: 30
      TOR_MaxCircuitDirtiness: 30
      PASSWORD: 123456
  zrrk:
    build: .
    network_mode: "host"
    links:
      - "proxy:proxy"
