version: "3"
name: "bili-live-spider"
services:
  proxy:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    network_mode: "host"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "200M"
      replicas: 1
    image: dperson/torproxy
    expose:
      - 9050
      - 9051
    environment:
      TOR_NewCircuitPeriod: 30
      TOR_MaxCircuitDirtiness: 30
      PASSWORD: 123456
  zrrk:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    build: .
    network_mode: "host"
    links:
      - "proxy:proxy"
